// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsgaakkwclsxdtysjxuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZ2Fha2t3Y2xzeGR0eXNqeHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTE2NzcsImV4cCI6MjA2NDk2NzY3N30._VPgjixGLyEP5cHHjOTKmONHGUN748VBjX_RE_X5s8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);